import Main from "./Main";
import "./globals.css";

export const metadata = {
  title: "VentasINP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Main>{children}</Main>
    </html>
  );
}
